modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="assets/islandcore/icon.png"
authors="SkyFramework Team"
description='''
Núcleo del sistema de islas flotantes para servidores NeoForge 1.21.1 — puerto de IslandCore (Fabric).
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="SERVER"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="SERVER"
